<a href="https://colab.research.google.com/github/suyashmarathe512/suyash/blob/main/Titantic_prediction_with_tf_decision_forests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Titanic Prediciton with TF Decision Forests**

This notebook will take you through the steps needed to train a baseline Gradient Boosted Trees Model using TensorFlow Decision Forests and creating a submission on the Titanic prediction.

This notebook shows:

1] How to do some basic pre-processing. For example, the passenger names will be tokenized, and ticket names will be splitted in parts.
2] How to train a Gradient Boosted Trees (GBT) with default parameters
3] How to train a GBT with improved default parameters
4] How to tune the parameters of a GBTs
5] How to train and ensemble many GBTs

# **Imports dependencies**

In [ ]:
import numpy as np
import pandas as pd
import os

import tensorflow as tf

import ydf

#model = ydf.RandomForestLearner(label="l").train(ds)
print(f"Found TF-DF {tfdf.__version__}")

Found TF-DF 1.11.0

# **Load dataset**

In [ ]:
train_df = pd.read_csv("/content/Titanic_Dataset/train.csv")
serving_df = pd.read_csv("/content/Titanic_Dataset/test.csv")

train_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# Prepare dataset

We will apply the following transformations on the dataset.

Tokenize the names. For example, "Braund, Mr. Owen Harris" will become ["Braund", "Mr.", "Owen", "Harris"].

Extract any prefix in the ticket. For example ticket "STON/O2. 3101282" will become "STON/O2." and 3101282.**

In [ ]:
def preprocess(df):
    df = df.copy()

    def normalize_name(x):
        return " ".join([v.strip(",()[].\"'") for v in x.split(" ")])

    def ticket_number(x):
        return x.split(" ")[-1]

    def ticket_item(x):
        items = x.split(" ")
        if len(items) == 1:
            return "NONE"
        return "_".join(items[0:-1])

    df["Name"] = df["Name"].apply(normalize_name)
    df["Ticket_number"] = df["Ticket"].apply(ticket_number)
    df["Ticket_item"] = df["Ticket"].apply(ticket_item)
    return df

preprocessed_train_df = preprocess(train_df)
preprocessed_serving_df = preprocess(serving_df)

preprocessed_train_df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Ticket_number,Ticket_item
0,1,0,3,Braund Mr Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S,21171,A/5
1,2,1,1,Cumings Mrs John Bradley Florence Briggs Thayer,female,38.0,1,0,PC 17599,71.2833,C85,C,17599,PC
2,3,1,3,Heikkinen Miss Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3101282,STON/O2.
3,4,1,1,Futrelle Mrs Jacques Heath Lily May Peel,female,35.0,1,0,113803,53.1000,C123,S,113803,NONE
4,5,0,3,Allen Mr William Henry,male,35.0,0,0,373450,8.0500,NaN,S,373450,NONE

In [ ]:
input_features = list(preprocessed_train_df.columns)
input_features.remove("Ticket")
input_features.remove("PassengerId")
input_features.remove("Survived")
#input_features.remove("Ticket_number")

print(f"Input features: {input_features}")

Input features: ['Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked', 'Ticket_number', 'Ticket_item']

# **Convert Pandas dataset to TensorFlow Dataset**

In [ ]:
train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(preprocessed_train_df,label="Survived").map(tokenize_names)
serving_ds = tfdf.keras.pd_dataframe_to_tf_dataset(preprocessed_serving_df).map(tokenize_names)

# **Train model with default parameters**

In [ ]:
model = tfdf.keras.GradientBoostedTreesModel(
    verbose=2, # Very few logs
    features=[tfdf.keras.FeatureUsage(name=n) for n in input_features],
    exclude_non_specified_features=True, # Only use the features in "features"
    random_seed=1234,
)
model.fit(train_ds)

self_evaluation = model.make_inspector().evaluation()
print(f"Accuracy: {self_evaluation.accuracy} Loss:{self_evaluation.loss}")

Use 2 thread(s) for training
Use /tmp/tmp2boavido as temporary training directory
Reading training dataset...
Training tensor examples:
Features: {'PassengerId': <tf.Tensor 'data:0' shape=(None,) dtype=int64>, 'Pclass': <tf.Tensor 'data_1:0' shape=(None,) dtype=int64>, 'Name': tf.RaggedTensor(values=Tensor("data_2:0", shape=(None,), dtype=string), row_splits=Tensor("data_3:0", shape=(None,), dtype=int64)), 'Sex': <tf.Tensor 'data_4:0' shape=(None,) dtype=string>, 'Age': <tf.Tensor 'data_5:0' shape=(None,) dtype=float64>, 'SibSp': <tf.Tensor 'data_6:0' shape=(None,) dtype=int64>, 'Parch': <tf.Tensor 'data_7:0' shape=(None,) dtype=int64>, 'Ticket': <tf.Tensor 'data_8:0' shape=(None,) dtype=string>, 'Fare': <tf.Tensor 'data_9:0' shape=(None,) dtype=float64>, 'Cabin': <tf.Tensor 'data_10:0' shape=(None,) dtype=string>, 'Embarked': <tf.Tensor 'data_11:0' shape=(None,) dtype=string>, 'Ticket_number': <tf.Tensor 'data_12:0' shape=(None,) dtype=string>, 'Ticket_item': <tf.Tensor 'data_13:0' shape=(None,) dtype=string>}
Label: Tensor("data_14:0", shape=(None,), dtype=int64)
Weights: None
Normalized tensor features:
 {'Pclass': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'Cast:0' shape=(None,) dtype=float32>), 'Name': SemanticTensor(semantic=<Semantic.CATEGORICAL_SET: 4>, tensor=tf.RaggedTensor(values=Tensor("data_2:0", shape=(None,), dtype=string), row_splits=Tensor("data_3:0", shape=(None,), dtype=int64))), 'Sex': SemanticTensor(semantic=<Semantic.CATEGORICAL: 2>, tensor=<tf.Tensor 'data_4:0' shape=(None,) dtype=string>), 'Age': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'Cast_1:0' shape=(None,) dtype=float32>), 'SibSp': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'Cast_2:0' shape=(None,) dtype=float32>), 'Parch': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'Cast_3:0' shape=(None,) dtype=float32>), 'Fare': SemanticTensor(semantic=<Semantic.NUMERICAL: 1>, tensor=<tf.Tensor 'Cast_4:0' shape=(None,) dtype=float32>), 'Cabin': SemanticTensor(semantic=<Semantic.CATEGORICAL: 2>, tensor=<tf.Tensor 'data_10:0' shape=(None,) dtype=string>), 'Embarked': SemanticTensor(semantic=<Semantic.CATEGORICAL: 2>, tensor=<tf.Tensor 'data_11:0' shape=(None,) dtype=string>), 'Ticket_number': SemanticTensor(semantic=<Semantic.CATEGORICAL: 2>, tensor=<tf.Tensor 'data_12:0' shape=(None,) dtype=string>), 'Ticket_item': SemanticTensor(semantic=<Semantic.CATEGORICAL: 2>, tensor=<tf.Tensor 'data_13:0' shape=(None,) dtype=string>)}
Training dataset read in 0:00:00.485479. Found 891 examples.
Training model...
Standard output detected as not visible to the user e.g. running in a notebook. Creating a training log redirection. If training gets stuck, try calling tfdf.keras.set_training_logs_redirection(False).

2024-11-23 06:46:49.004847: W external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:1840] "goss_alpha" set but "sampling_method" not equal to "GOSS".
2024-11-23 06:46:49.005243: W external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:1850] "goss_beta" set but "sampling_method" not equal to "GOSS".
2024-11-23 06:46:49.005339: W external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:1864] "selective_gradient_boosting_ratio" set but "sampling_method" not equal to "SELGB".
2024-11-23 06:46:49.005956: I external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:575] Default loss set to BINOMIAL_LOG_LIKELIHOOD
2024-11-23 06:46:49.006032: I external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:1188] Training gradient boosted tree on 891 example(s) and 11 feature(s).
2024-11-23 06:46:49.008087: I external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:1228] 799 examples used for training and 92 examples used for validation
2024-11-23 06:46:49.014244: I external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:1603] 	num-trees:1 train-loss:1.217019 train-accuracy:0.624531 valid-loss:1.312529 valid-accuracy:0.543478
2024-11-23 06:46:49.309569: I external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:1640] Create final snapshot of the model at iteration 60
2024-11-23 06:46:49.315857: I external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:277] Truncates the model to 31 tree(s) i.e. 31  iteration(s).
2024-11-23 06:46:49.316769: I external/ydf/yggdrasil_decision_forests/learner/gradient_boosted_trees/gradient_boosted_trees.cc:339] Final model num-trees:31 valid-loss:0.860894 valid-accuracy:0.826087
2024-11-23 06:46:49.345771: I tensorflow_decision_forests/tensorflow/ops/inference/kernel.cc:1206] Loading model from path /tmp/tmp2boavido/model/ with prefix a2e5befd305340d9
I0000 00:00:1732344409.351626    1328 abstract_model.cc:1404] Engine "GradientBoostedTreesQuickScorerExtended" built
2024-11-23 06:46:49.351682: I tensorflow_decision_forests/tensorflow/ops/inference/kernel.cc:1035] Use fast generic engine

Model trained in 0:00:00.381055
Compiling model...
Model compiled.
Accuracy: 0.8260869383811951 Loss:0.8608942627906799

# **Train model with improved default parameters**

In [ ]:
model = tfdf.keras.GradientBoostedTreesModel(
    verbose=0, # Very few logs
    features=[tfdf.keras.FeatureUsage(name=n) for n in input_features],
    exclude_non_specified_features=True, # Only use the features in "features"

    min_examples=1,
    categorical_algorithm="RANDOM",
    shrinkage=0.05,
    split_axis="SPARSE_OBLIQUE",
    sparse_oblique_normalization="MIN_MAX",
    sparse_oblique_num_projections_exponent=2.0,
    num_trees=2000,
    random_seed=1234,

)
model.fit(train_ds)

self_evaluation = model.make_inspector().evaluation()
print(f"Accuracy: {self_evaluation.accuracy} Loss:{self_evaluation.loss}")

Accuracy: 0.75 Loss:1.0462466478347778

In [ ]:
model.summary()

Model: "gradient_boosted_trees_model_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
=================================================================
Total params: 1 (1.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 1 (1.00 Byte)
_________________________________________________________________
Type: "GRADIENT_BOOSTED_TREES"
Task: CLASSIFICATION
Label: "__LABEL"

Input Features (11):
	Age
	Cabin
	Embarked
	Fare
	Name
	Parch
	Pclass
	Sex
	SibSp
	Ticket_item
	Ticket_number

No weights

Variable Importance: INV_MEAN_MIN_DEPTH:
    1.           "Sex"  0.805245 ################
    2.           "Age"  0.372369 #####
    3.          "Fare"  0.273026 ##
    4.          "Name"  0.187307
    5.        "Pclass"  0.180805
    6.   "Ticket_item"  0.178416
    7. "Ticket_number"  0.178366
    8.         "Parch"  0.177684
    9.      "Embarked"  0.176070
   10.         "SibSp"  0.172557

Variable Importance: NUM_AS_ROOT:
    1.  "Sex" 34.000000 ################
    2. "Name"  2.000000

Variable Importance: NUM_NODES:
    1.           "Age" 428.000000 ################
    2.          "Fare" 278.000000 ##########
    3.          "Name" 55.000000 #
    4.   "Ticket_item" 38.000000 #
    5.           "Sex" 36.000000 #
    6. "Ticket_number" 23.000000
    7.         "Parch" 19.000000
    8.        "Pclass" 10.000000
    9.      "Embarked"  9.000000
   10.         "SibSp"  4.000000

Variable Importance: SUM_SCORE:
    1.           "Sex" 461.523208 ################
    2.           "Age" 378.019156 #############
    3.          "Fare" 275.230253 #########
    4.          "Name" 118.343331 ####
    5.        "Pclass" 36.228439 #
    6.         "Parch" 23.516134
    7.   "Ticket_item" 21.838539
    8. "Ticket_number" 17.217955
    9.      "Embarked"  7.074696
   10.         "SibSp"  0.400482



Loss: BINOMIAL_LOG_LIKELIHOOD
Validation loss value: 1.04625
Number of trees per iteration: 1
Node format: NOT_SET
Number of trees: 36
Total number of nodes: 1836

Number of nodes by tree:
Count: 36 Average: 51 StdDev: 4.49691
Min: 41 Max: 61 Ignored: 0
----------------------------------------------
[ 41, 42)  1   2.78%   2.78% #
[ 42, 43)  0   0.00%   2.78%
[ 43, 44)  1   2.78%   5.56% #
[ 44, 45)  0   0.00%   5.56%
[ 45, 46)  3   8.33%  13.89% ###
[ 46, 47)  0   0.00%  13.89%
[ 47, 48)  5  13.89%  27.78% #####
[ 48, 49)  0   0.00%  27.78%
[ 49, 50)  3   8.33%  36.11% ###
[ 50, 51)  0   0.00%  36.11%
[ 51, 52) 10  27.78%  63.89% ##########
[ 52, 53)  0   0.00%  63.89%
[ 53, 54)  3   8.33%  72.22% ###
[ 54, 55)  0   0.00%  72.22%
[ 55, 56)  5  13.89%  86.11% #####
[ 56, 57)  0   0.00%  86.11%
[ 57, 58)  3   8.33%  94.44% ###
[ 58, 59)  0   0.00%  94.44%
[ 59, 60)  1   2.78%  97.22% #
[ 60, 61]  1   2.78% 100.00% #

Depth by leafs:
Count: 936 Average: 4.81624 StdDev: 0.493973
Min: 3 Max: 5 Ignored: 0
----------------------------------------------
[ 3, 4)  44   4.70%   4.70% #
[ 4, 5)  84   8.97%  13.68% #
[ 5, 5] 808  86.32% 100.00% ##########

Number of training obs by leaf:
Count: 936 Average: 30.7308 StdDev: 73.3279
Min: 1 Max: 458 Ignored: 0
----------------------------------------------
[   1,  23) 723  77.24%  77.24% ##########
[  23,  46)  71   7.59%  84.83% #
[  46,  69)  42   4.49%  89.32% #
[  69,  92)  20   2.14%  91.45%
[  92, 115)   2   0.21%  91.67%
[ 115, 138)   7   0.75%  92.41%
[ 138, 161)  27   2.88%  95.30%
[ 161, 184)   8   0.85%  96.15%
[ 184, 207)   2   0.21%  96.37%
[ 207, 230)   4   0.43%  96.79%
[ 230, 252)   2   0.21%  97.01%
[ 252, 275)   0   0.00%  97.01%
[ 275, 298)   0   0.00%  97.01%
[ 298, 321)   1   0.11%  97.12%
[ 321, 344)   0   0.00%  97.12%
[ 344, 367)   5   0.53%  97.65%
[ 367, 390)  11   1.18%  98.82%
[ 390, 413)   4   0.43%  99.25%
[ 413, 436)   6   0.64%  99.89%
[ 436, 458]   1   0.11% 100.00%

Attribute in nodes:
	428 : Age [NUMERICAL]
	278 : Fare [NUMERICAL]
	55 : Name [CATEGORICAL_SET]
	38 : Ticket_item [CATEGORICAL]
	36 : Sex [CATEGORICAL]
	23 : Ticket_number [CATEGORICAL]
	19 : Parch [NUMERICAL]
	10 : Pclass [NUMERICAL]
	9 : Embarked [CATEGORICAL]
	4 : SibSp [NUMERICAL]

Attribute in nodes with depth <= 0:
	34 : Sex [CATEGORICAL]
	2 : Name [CATEGORICAL_SET]

Attribute in nodes with depth <= 1:
	44 : Age [NUMERICAL]
	34 : Sex [CATEGORICAL]
	21 : Fare [NUMERICAL]
	5 : Pclass [NUMERICAL]
	2 : Name [CATEGORICAL_SET]
	1 : Ticket_number [CATEGORICAL]
	1 : Parch [NUMERICAL]

Attribute in nodes with depth <= 2:
	111 : Age [NUMERICAL]
	75 : Fare [NUMERICAL]
	35 : Sex [CATEGORICAL]
	7 : Name [CATEGORICAL_SET]
	6 : Parch [NUMERICAL]
	5 : Pclass [NUMERICAL]
	5 : Embarked [CATEGORICAL]
	4 : Ticket_number [CATEGORICAL]
	4 : Ticket_item [CATEGORICAL]

Attribute in nodes with depth <= 3:
	239 : Age [NUMERICAL]
	155 : Fare [NUMERICAL]
	36 : Sex [CATEGORICAL]
	18 : Name [CATEGORICAL_SET]
	13 : Ticket_number [CATEGORICAL]
	12 : Ticket_item [CATEGORICAL]
	10 : Parch [NUMERICAL]
	6 : Pclass [NUMERICAL]
	6 : Embarked [CATEGORICAL]
	1 : SibSp [NUMERICAL]

Attribute in nodes with depth <= 5:
	428 : Age [NUMERICAL]
	278 : Fare [NUMERICAL]
	55 : Name [CATEGORICAL_SET]
	38 : Ticket_item [CATEGORICAL]
	36 : Sex [CATEGORICAL]
	23 : Ticket_number [CATEGORICAL]
	19 : Parch [NUMERICAL]
	10 : Pclass [NUMERICAL]
	9 : Embarked [CATEGORICAL]
	4 : SibSp [NUMERICAL]

Condition type in nodes:
	739 : ObliqueCondition
	117 : ContainsBitmapCondition
	44 : ContainsCondition
Condition type in nodes with depth <= 0:
	36 : ContainsBitmapCondition
Condition type in nodes with depth <= 1:
	71 : ObliqueCondition
	37 : ContainsBitmapCondition
Condition type in nodes with depth <= 2:
	197 : ObliqueCondition
	50 : ContainsBitmapCondition
	5 : ContainsCondition
Condition type in nodes with depth <= 3:
	411 : ObliqueCondition
	70 : ContainsBitmapCondition
	15 : ContainsCondition
Condition type in nodes with depth <= 5:
	739 : ObliqueCondition
	117 : ContainsBitmapCondition
	44 : ContainsCondition

Training logs:
Number of iteration to final model: 36
	Iter:1 train-loss:1.267677 valid-loss:1.369485  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:2 train-loss:1.214848 valid-loss:1.331812  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:3 train-loss:1.164942 valid-loss:1.291869  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:4 train-loss:1.120759 valid-loss:1.258706  train-accuracy:0.624531 valid-accuracy:0.543478
	Iter:5 train-loss:1.079912 valid-loss:1.231839  train-accuracy:0.809762 valid-accuracy:0.717391
	Iter:6 train-loss:1.043659 valid-loss:1.209835  train-accuracy:0.817272 valid-accuracy:0.717391
	Iter:16 train-loss:0.793468 valid-loss:1.096304  train-accuracy:0.903630 valid-accuracy:0.739130
	Iter:26 train-loss:0.655063 valid-loss:1.069241  train-accuracy:0.921151 valid-accuracy:0.750000
	Iter:36 train-loss:0.562198 valid-loss:1.046247  train-accuracy:0.928661 valid-accuracy:0.750000
	Iter:46 train-loss:0.498899 valid-loss:1.064525  train-accuracy:0.932416 valid-accuracy:0.760870
	Iter:56 train-loss:0.455454 valid-loss:1.085791  train-accuracy:0.939925 valid-accuracy:0.750000
	Iter:66 train-loss:0.409738 valid-loss:1.107281  train-accuracy:0.946183 valid-accuracy:0.750000

# **Make predictions**

In [ ]:
proba_survive = model.predict(serving_ds, verbose=0)[:,0]
prediciton = pd.DataFrame({"PassengerId": serving_df["PassengerId"],"Survived": (proba_survive >= 0.05).astype(int)})
print(prediciton)

     PassengerId  Survived
0            892         1
1            893         1
2            894         1
3            895         1
4            896         1
..           ...       ...
413         1305         1
414         1306         1
415         1307         1
416         1308         1
417         1309         1

[418 rows x 2 columns]

# **Training a model with hyperparameter tunning**

In [ ]:
tuner = tfdf.tuner.RandomSearch(num_trials=1000)
tuner.choice("min_examples", [2, 5, 7, 10])
tuner.choice("categorical_algorithm", ["CART", "RANDOM"])

local_search_space = tuner.choice("growing_strategy", ["LOCAL"])
local_search_space.choice("max_depth", [3, 4, 5, 6, 8])

global_search_space = tuner.choice("growing_strategy", ["BEST_FIRST_GLOBAL"], merge=True)
global_search_space.choice("max_num_nodes", [16, 32, 64, 128, 256])

#tuner.choice("use_hessian_gain", [True, False])
tuner.choice("shrinkage", [0.02, 0.05, 0.10, 0.15])
tuner.choice("num_candidate_attributes_ratio", [0.2, 0.5, 0.9, 1.0])


tuner.choice("split_axis", ["AXIS_ALIGNED"])
oblique_space = tuner.choice("split_axis", ["SPARSE_OBLIQUE"], merge=True)
oblique_space.choice("sparse_oblique_normalization",
                     ["NONE", "STANDARD_DEVIATION", "MIN_MAX"])
oblique_space.choice("sparse_oblique_weights", ["BINARY", "CONTINUOUS"])
oblique_space.choice("sparse_oblique_num_projections_exponent", [1.0, 1.5])

# Tune the model. Notice the `tuner=tuner`.
tuned_model = tfdf.keras.GradientBoostedTreesModel(tuner=tuner)
tuned_model.fit(train_ds, verbose=0)

tuned_self_evaluation = tuned_model.make_inspector().evaluation()
print(f"Accuracy: {tuned_self_evaluation.accuracy} Loss:{tuned_self_evaluation.loss}")

Use /tmp/tmp8ue5kfbw as temporary training directory
Accuracy: 0.8630136847496033 Loss:0.6749962568283081

# Making an ensemble
Here you'll create 100 models with different seeds and combine their results

This approach removes a little bit the random aspects related to creating ML models

In the GBT creation is used the honest parameter. It will use different training examples to infer the structure and the leaf values. This regularization technique trades examples for bias estimates.**

In [ ]:
predictions = None
num_predictions = 0

for i in range(100):
    print(f"i:{i}")
    # Possible models: GradientBoostedTreesModel or RandomForestModel
    model = tfdf.keras.GradientBoostedTreesModel(
        verbose=0, # Very few logs
        features=[tfdf.keras.FeatureUsage(name=n) for n in input_features],
        exclude_non_specified_features=True, # Only use the features in "features"

        #min_examples=1,
        #categorical_algorithm="RANDOM",
        ##max_depth=4,
        #shrinkage=0.05,
        ##num_candidate_attributes_ratio=0.2,
        #split_axis="SPARSE_OBLIQUE",
        #sparse_oblique_normalization="MIN_MAX",
        #sparse_oblique_num_projections_exponent=2.0,
        #num_trees=2000,
        ##validation_ratio=0.0,
        random_seed=i,
        honest=True,
    )
    model.fit(train_ds)

    sub_predictions = model.predict(serving_ds, verbose=0)[:,0]
    if predictions is None:
        predictions = sub_predictions
    else:
        predictions += sub_predictions
    num_predictions += 1

predictions/=num_predictions
predictions = pd.DataFrame({
        "PassengerId": serving_df["PassengerId"],
        "Survived": (predictions >= 0.5).astype(int)
    })

print(predictions)

i:0
i:1
i:2
i:3
i:4
i:5
i:6
i:7
i:8
i:9
i:10
i:11
i:12
i:13
i:14
i:15
i:16
i:17
i:18
i:19
i:20
i:21
i:22
i:23
i:24
i:25
i:26
i:27
i:28
i:29
i:30
i:31
i:32
i:33
i:34
i:35
i:36
i:37
i:38
i:39
i:40
i:41
i:42
i:43
i:44
i:45
i:46
i:47
i:48
i:49
i:50
i:51
i:52
i:53
i:54
i:55
i:56
i:57
i:58
i:59
i:60
i:61
i:62
i:63
i:64
i:65
i:66
i:67
i:68
i:69
i:70
i:71
i:72
i:73
i:74
i:75
i:76
i:77
i:78
i:79
i:80
i:81
i:82
i:83
i:84
i:85
i:86
i:87
i:88
i:89
i:90
i:91
i:92
i:93
i:94
i:95
i:96
i:97
i:98
i:99
     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]